### ISSUE TITLE
Finding Albums More Cleverly

### ISSUE THREAD

**Issue by mnzaki** [keenerd/albumbler#4]
My music directory is organized a bit differently than simple "artist -> album" hierarchies. I have a big collection and parts of it are organized differently, with album dirs at different depths for various reasons. Albumbler's simple assumptions lead to either loading 100s of songs from several artists, or nothing at all. 

I have thought of two ways to more reliably find album dirs:
1) Find the deepest dir that contains only music files and no subdirectories
This does not allow playing files that are in the top dirs with no artist/album parent dirs. I tried to do this by listing all such dirs with a bash command and just adding them to music_paths but it didn't work reliably and mpd wasn't happy with a lot of the paths (they need to be stripped upto the main music dir as configured in mpd)
2) Allow something with more data to take care of this
Essentially I just used mpd's knowledge of artists and albums. I just list all albums and their artist and choose an album like that. This is of course a LOT more reliable.

So I was wondering would there be any interest in extending (abstracting, essentially) albumbler to allow for different ways of album/playlist discovery? I have hacked my copy to make playlist a list of "(artist, album)" tuples as mentioned above, and the main algorithm didn't mind at all that 'play' was now not a string, thanks to python's type system. Of course changes were required in the command and notification part.

**Comment by mnzaki** [comment]
I discarded my hacky solution and wrote up a more proper implementation at https://github.com/mnzaki/albumbler/commits/ 
Thoughts? Is this complicating things too much?

**Comment by keenerd** [comment]
Took a very good hard look at your patch.  I like parts of it, just nothing to do with the big OOP push in the abstract playlist gen.  (mnzaki@d1684afe0c14a022e9b07cc8c773dde9eb4b6fac).  The general layout is not too sensible and there are a few technical issues like mixing old and new style classes, selfless methods and some other weirdness.  I really like the MPDAlbumsProvider(), but I'll have to rewrite that big patch in the middle first.

**Comment by keenerd** [comment]
How is bdf08c8481 for you?

**Comment by mnzaki** [comment]
Looks fine. Much gentler push into OOP land :D I made a few comments, mostly nitpicks but two important ones: music_player.reasonable() and behaviour of player = 'mpd' in config
